# Generated by Django 4.0.4 on 2022-06-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='handle',
            field=models.CharField(default='aaa', max_length=256),
            preserve_default=False,
        ),
    ]
