# Generated by Django 4.0.4 on 2022-06-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces_app', '0003_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='index',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
