# Generated by Django 4.0.4 on 2022-06-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces_app', '0004_contestant_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='handle',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
