# Generated by Django 4.0.4 on 2022-06-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces_app', '0005_alter_contestant_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
