# Generated by Django 4.0.4 on 2022-06-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces_app', '0006_alter_data_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='handle_with_case',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
