name: Testing
on: push
jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip3 install django
        pip3 install requests
        
        python3 mamange.py test
